{% set name = "schemdraw" %}
{% set version = "0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/schemdraw-{{ version }}.tar.gz
  sha256: f39183f3090e607c7dbc41ebd3dddf2ae0ef1c81dcbab6c6e2429599559bd7e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - schemdraw
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://schemdraw.readthedocs.io/
  summary: Electrical circuit schematic drawing
  dev_url: https://bitbucket.org/cdelker/schemdraw
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkozel
